service: user-service

frameworkVersion: "3.39.0"

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x

functions:
  getUsers:
    handler: src/handler.getUsers
    events:
      - http:
          path: users
          method: get
  getUser:
    handler: src/handler.getUser
    events:
      - http:
          path: users/{id}
          method: get
  createUser:
    handler: src/handler.createUser
    events:
      - http:
          path: users
          method: post
  updateUser:
    handler: src/handler.updateUser
    events:
      - http:
          path: users/{id}
          method: patch

custom:
  serverless-offline:
    port: 3000
    host: localhost
